name: Go Service CI

on: [push]

jobs:
  build:
    name: Build Go Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v1
    - name: Execute Build
      uses: actions/docker/cli@master
      with:
        args: build -t ${{ github.repository }}:${{ github.sha }} .
    timeout-minutes: 3