name: CI

on: [push]

jobs:
  build:
    name: Building Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Service Source Code
      uses: actions/checkout@v1
    - name: Build Service
      uses: actions/docker/cli@master
      with:
        args: build -t ${{github.repository}}:${{github.sha}} .