name: Go Service CI

on: [push]

jobs:
  build:
    name: Checkout, Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Build image
      uses: actions/docker/cli@master
      with:
        args: build -t ${{ github.repository }}:${{ github.sha }} .
    - name: Login to image reposotory
      uses: actions/docker/cli@master
      with:
        args: login --username=bpmericle --password=${{ secrets.ImageRepositoryPassword }}
    - name: Push image to image reposotory
      uses: actions/docker/cli@master
      with:
        args: push ${{ github.repository }}:${{ github.sha }}
    timeout-minutes: 4
  pull_image_from_repo:
    name: Login and Pull Image from Image Repository
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Pull image from image reposotory
      uses: actions/docker/cli-multi@master
      with:
        args: |
          login --username=bpmericle --password=${{ secrets.ImageRepositoryPassword }}
          pull ${{ github.repository }}:${{ github.sha }}
#    - name: Login to image reposotory
#      uses: actions/docker/cli@master
#      with:
#        args: login --username=bpmericle --password=${{ secrets.ImageRepositoryPassword }}
#    - name: Pull image from image reposotory
#      uses: actions/docker/cli@master
#      with:
#        args: pull ${{ github.repository }}:${{ github.sha }}
    timeout-minutes: 1