name: CI

on: [push]

jobs:
  build:
    name: Build service action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Run multi-stage Docker build
      uses: actions/docker/cli@master