name: Go Service CI

on: [push]

jobs:
  build:
    name: Checkout and Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Execute image build
      uses: actions/docker/cli@master
      with:
        args: build -t ${{ github.repository }}:${{ github.sha }} .
    timeout-minutes: 3
  push_to_repo:
    name: Login and Push Image to Image Repository
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to image reposotory
      uses: actions/docker/cli@master
      with:
        args: login --username=bpmericle --password=${{ secrets.ImageRepositoryPassword }}
    - name: Push image to image reposotory
      uses: actions/docker/cli@master
      with:
        args: push ${{ github.repository }}:${{ github.sha }}
    timeout-minutes: 2